"""Regenerate runs/INDEX.md -- one row per set of checkpoints under runs/.

    python -m algorithms.utils.index_runs

Two sources, kept strictly apart:

  the checkpoints    what was trained. Read from each run's `.run.yaml` sidecar
                     when it has one, and otherwise DECODED from the filename
                     (checkpoint_filename is close to lossless for the settings
                     it encodes). Anything neither source determines is left
                     blank -- never inferred.

  runs/notes.yaml    what you concluded. Status and a sentence of judgement,
                     hand-written, merged in here and never written back to, so
                     regenerating the index cannot clobber it.

The index is disposable; notes.yaml and the sidecars are not.
"""
import argparse
import datetime
import re
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from algorithms.utils.io_utils import load_run_config, run_stem  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
RUNS = REPO / "runs"
NOTES = RUNS / "notes.yaml"
INDEX = RUNS / "INDEX.md"

_STATUS_ORDER = {"valid": 0, "unknown": 1, "superseded": 2, "corrupt": 3}


def decode_stem(stem):
    """Recover what the filename encodes. The inverse of checkpoint_filename.

    Partial by construction: it only ever reports tokens that are present, so a
    setting left at its default (and therefore unmarked) comes back as absent
    rather than as a value this function made up.
    """
    out = {}
    if m := re.search(r"_seed(\d+)", stem):
        out["seed"] = int(m.group(1))
    if m := re.search(r"_agents(\d+)", stem):
        out["agents"] = int(m.group(1))
    if m := re.search(r"_reward_(\w+?)(?:_|$)", stem):
        out["reward"] = m.group(1)

    parts = []
    if m := re.search(r"_pay_(on|noop)", stem):
        scheme = "tithe" if "_tithe" in stem else "instant"
        parts.append(f"pay={m.group(1)}/{scheme}" + (" split" if "_split" in stem else ""))
    for mode in ("bargain", "negotiate", "solver", "reinforce"):
        if f"_{mode}" in stem:
            label = mode
            if mode == "negotiate" and (m := re.search(r"_nu(\d+|all)", stem)):
                label += f" nu={m.group(1)}"
            if mode == "bargain":
                if m := re.search(r"_seg(\d+)", stem):
                    label += f" seg={m.group(1)}"
                if m := re.search(r"_q(majority|\d+)", stem):
                    label += f" q={m.group(1)}"
            parts.append(label)
            break
    if "_joint" in stem:
        parts.append("joint")
    if m := re.search(r"_null([\d.]+)", stem):
        parts.append(f"null={m.group(1)}")
    out["mechanism"] = " ".join(parts) or "IPPO"
    return out


def scan(root=RUNS):
    """One record per (directory, run stem) that has checkpoints under `root`."""
    groups = {}
    for pkl in sorted(root.rglob("*.pkl")):
        groups.setdefault(run_stem(str(pkl)), []).append(pkl)

    records = []
    for stem, files in sorted(groups.items()):
        stem_path = Path(stem)
        cfg = load_run_config(stem) or {}
        env_kwargs = cfg.get("ENV_KWARGS") or {}
        decoded = decode_stem(stem_path.name)
        low, high = cfg.get("CONTRACT_LOW"), cfg.get("CONTRACT_HIGH")
        records.append({
            "dir": stem_path.parent.relative_to(REPO).as_posix(),
            "stem": stem_path.name,
            "files": len(files),
            "modified": datetime.date.fromtimestamp(
                max(f.stat().st_mtime for f in files)).isoformat(),
            "seed": cfg.get("SEED", decoded.get("seed")),
            "agents": env_kwargs.get("num_agents", decoded.get("agents")),
            "mechanism": decoded.get("mechanism", ""),
            "theta": (f"[{low:g}, {high:g}]"
                      if low is not None and high is not None else ""),
            "sidecar": bool(cfg),
            "provenance": (cfg.get("_provenance") or {}).get("source", ""),
        })
    return records


def render(records, notes):
    """The whole INDEX.md, as one string."""
    lines = [
        "# Run index",
        "",
        f"Generated by `python -m algorithms.utils.index_runs` on "
        f"{datetime.date.today().isoformat()}. **Do not hand-edit** -- put "
        f"judgement in [notes.yaml](notes.yaml), which is merged in below and "
        f"never overwritten.",
        "",
        "`theta` is the contract range the run was TRAINED on. Blank means no "
        "sidecar recorded it: the bounds are not in the filename, and replaying "
        "at the wrong ones silently rescales theta, so recover them from wandb "
        "before quoting any theta from that run.",
        "",
    ]

    def lookup(record):
        """Most specific note wins; a note on a parent directory covers its tree.

        So one entry for `runs/Old` speaks for all 30-odd runs beneath it, and a
        single run can still be called out by its own path.
        """
        candidates = [f"{record['dir']}/{record['stem']}", record["dir"]]
        candidates += [p.as_posix() for p in Path(record["dir"]).parents
                       if p.as_posix() not in (".", "runs")]
        for key in candidates:
            if key in notes:
                return key, (notes[key] or {})
        return None, {}

    by_status = {}
    for r in records:
        r["note_key"], note = lookup(r)
        r["status"] = note.get("status", "unknown")
        r["note"] = " ".join(str(note.get("note", "")).split())
        by_status.setdefault(r["status"], []).append(r)

    for status in sorted(by_status, key=lambda s: (_STATUS_ORDER.get(s, 9), s)):
        rows = by_status[status]
        lines += [f"## {status} ({len(rows)})", ""]
        lines += ["| run | mechanism | agents | seed | theta | files | modified |",
                  "|---|---|---|---|---|---|---|"]
        for r in sorted(rows, key=lambda x: x["dir"]):
            flag = "" if r["sidecar"] else " ⚠"
            lines.append(
                f"| [{r['dir']}]({Path(r['dir']).relative_to('runs').as_posix()}/)"
                f"{flag} | {r['mechanism']} | {r['agents'] or ''} | "
                f"{r['seed'] or ''} | {r['theta'] or '—'} | {r['files']} | "
                f"{r['modified']} |")
        lines.append("")
        # One bullet per NOTE, not per run: a note on a parent directory covers
        # every run beneath it and should be stated once.
        seen = {}
        for r in sorted(rows, key=lambda x: x["dir"]):
            if r["note"] and r["note_key"] not in seen:
                seen[r["note_key"]] = r["note"]
        for key, note in seen.items():
            lines.append(f"- **{key}** — {note}")
        if seen:
            lines.append("")

    missing = [r for r in records if not r["sidecar"]]
    lines += [
        "---",
        "",
        f"⚠ = no `.run.yaml` sidecar ({len(missing)} of {len(records)}). Those "
        f"predate the sidecar mechanism; everything shown for them is decoded "
        f"from the filename alone. Runs trained from now on record their "
        f"resolved config automatically (`algorithms/utils/io_utils.save_run_config`).",
        "",
    ]
    return "\n".join(lines)


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--check", action="store_true",
                   help="exit 1 if INDEX.md is stale, instead of rewriting it")
    args = p.parse_args()

    if not RUNS.exists():
        raise SystemExit(f"no {RUNS}")
    notes = yaml.safe_load(NOTES.read_text()) if NOTES.exists() else {}
    text = render(scan(), notes or {})

    if args.check:
        current = INDEX.read_text() if INDEX.exists() else ""
        # The generated-on date changes daily and means nothing; compare the body.
        strip = lambda s: "\n".join(l for l in s.splitlines() if "Generated by" not in l)
        if strip(current) != strip(text):
            raise SystemExit("runs/INDEX.md is stale -- rerun index_runs")
        print("runs/INDEX.md is up to date")
        return

    INDEX.write_text(text)
    print(f"wrote {INDEX.relative_to(REPO)} "
          f"({len(scan())} runs, {sum(1 for r in scan() if not r['sidecar'])} "
          f"without a sidecar)")


if __name__ == "__main__":
    main()
